### ISSUE TITLE
What is the minimum kernel version?

### ISSUE THREAD

**Issue by jamesbond3142** [0x7375646F/Linuwu-Sense#32]
The README says this builds on 6.12, 6.13, 6.14 ... but I just tried building with 6.12.33 and experienced failure, see below. 

It seems that the problem is `platform_profile_ops` does not exist in 6.12. I tried to replace that with `platform_profile_handler` but it doesn't build either. 

```
sandbox# make
make -C /lib/modules/6.12.33/build M=/tmp/Linuwu-Sense modules
make[1]: Entering directory '/usr/src/linux-6.12.33'
  CC [M]  /tmp/Linuwu-Sense/src/linuwu_sense.o
/tmp/Linuwu-Sense/src/linuwu_sense.c:2245:22: error: variable ‘acer_predator_v4_platform_profile_ops’ has initializer but incomplete type
 2245 |  static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                      ^~~~~~~~~~~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2246:7: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2246 |      .probe = acer_predator_v4_platform_profile_probe,
      |       ^~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2246:15: warning: excess elements in struct initializer
 2246 |      .probe = acer_predator_v4_platform_profile_probe,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2246:15: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/tmp/Linuwu-Sense/src/linuwu_sense.c:2247:7: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2247 |      .profile_get = acer_predator_v4_platform_profile_get,
      |       ^~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2247:21: warning: excess elements in struct initializer
 2247 |      .profile_get = acer_predator_v4_platform_profile_get,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2247:21: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/tmp/Linuwu-Sense/src/linuwu_sense.c:2248:7: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2248 |      .profile_set = acer_predator_v4_platform_profile_set,
      |       ^~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2248:21: warning: excess elements in struct initializer
 2248 |      .profile_set = acer_predator_v4_platform_profile_set,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c:2248:21: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/tmp/Linuwu-Sense/src/linuwu_sense.c: In function ‘acer_platform_profile_setup’:
/tmp/Linuwu-Sense/src/linuwu_sense.c:2254:36: error: implicit declaration of function ‘devm_platform_profile_register’; did you mean ‘platform_profile_register’? [-Werror=implicit-function-declaration]
 2254 |          platform_profile_device = devm_platform_profile_register(
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    platform_profile_register
/tmp/Linuwu-Sense/src/linuwu_sense.c:2254:34: warning: assignment to ‘struct device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2254 |          platform_profile_device = devm_platform_profile_register(
      |                                  ^
/tmp/Linuwu-Sense/src/linuwu_sense.c: In function ‘acer_thermal_profile_change’:
/tmp/Linuwu-Sense/src/linuwu_sense.c:2339:10: error: too many arguments to function ‘platform_profile_notify’
 2339 |          platform_profile_notify(platform_profile_device);
      |          ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/Linuwu-Sense/src/linuwu_sense.c:22:
./include/linux/platform_profile.h:40:6: note: declared here
   40 | void platform_profile_notify(void);
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/Linuwu-Sense/src/linuwu_sense.c: At top level:
/tmp/Linuwu-Sense/src/linuwu_sense.c:2245:43: error: storage size of ‘acer_predator_v4_platform_profile_ops’ isn’t known
 2245 |  static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:229: /tmp/Linuwu-Sense/src/linuwu_sense.o] Error 1
make[2]: *** [/usr/src/linux-6.12.33/Makefile:1945: /tmp/Linuwu-Sense] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-6.12.33'
make: *** [Makefile:12: all] Error 2
```

**Comment by 0x7375646F** [comment]
https://github.com/0x7375646F/Linuwu-Sense/tree/v6.13
Try this ?
